language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t fenriss/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true fenriss/react-test npm test

after_success:
    - docker build -t fenriss/multi-client ./client
    - docker build -t fenriss/multi-nginx ./nginx
    - docker build -t fenriss/multi-server ./server
    - docker build -t fenriss/multi-worker ./worker

#log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#take images and push to docker hub
    - docker push fenriss/multi-client
    - docker push fenriss/multi-nginx
    - docker push fenriss/multi-server
    - docker push fenriss/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-370523591161
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY